import type { PdfTemplateDefinition } from '../formTypes';

export const demoAlliedHealthReferral: PdfTemplateDefinition = {
  id: 'demo-allied-health-referral',
  name: 'Demo Allied Health Referral',
  description:
    'Synthetic local-only form used to validate the browser PDF filling workflow.',
  templatePath: '/templates/demo-allied-health-referral.pdf',
  previewPath: '/templates/demo-allied-health-referral-preview.png',
  defaultDownloadName: 'allied-health-completed-form.pdf',
  sections: [
    {
      id: 'patient',
      title: 'Patient Details',
      description: 'Basic details needed on the referral form.',
      fields: [
        {
          id: 'patientName',
          label: 'Patient full name',
          type: 'text',
          required: true,
          autocomplete: 'off',
          validation: { maxLength: 80 },
          pdf: { mode: 'overlay', page: 0, x: 145, y: 692, size: 11, maxWidth: 380 },
        },
        {
          id: 'dateOfBirth',
          label: 'Date of birth',
          type: 'date',
          required: true,
          autocomplete: 'off',
          pdf: { mode: 'overlay', page: 0, x: 145, y: 665, size: 11, maxWidth: 150 },
        },
        {
          id: 'patientPhone',
          label: 'Phone',
          type: 'tel',
          required: true,
          autocomplete: 'off',
          validation: { pattern: '^[0-9 +()\\-]{8,20}$' },
          helpText: 'Use a direct contact number if available.',
          pdf: { mode: 'overlay', page: 0, x: 145, y: 639, size: 11, maxWidth: 150 },
        },
        {
          id: 'patientEmail',
          label: 'Email',
          type: 'email',
          autocomplete: 'off',
          validation: { maxLength: 120 },
          pdf: { mode: 'overlay', page: 0, x: 145, y: 613, size: 11, maxWidth: 380 },
        },
      ],
    },
    {
      id: 'referral',
      title: 'Referral Details',
      description: 'Information about the clinician and the requested service.',
      fields: [
        {
          id: 'referralDate',
          label: 'Referral date',
          type: 'date',
          required: true,
          autocomplete: 'off',
          pdf: { mode: 'overlay', page: 0, x: 145, y: 559, size: 11, maxWidth: 150 },
        },
        {
          id: 'clinicianName',
          label: 'Referring clinician',
          type: 'text',
          required: true,
          autocomplete: 'off',
          validation: { maxLength: 80 },
          pdf: { mode: 'overlay', page: 0, x: 145, y: 533, size: 11, maxWidth: 380 },
        },
        {
          id: 'providerNumber',
          label: 'Provider number',
          type: 'text',
          autocomplete: 'off',
          validation: { maxLength: 20 },
          pdf: { mode: 'overlay', page: 0, x: 145, y: 507, size: 11, maxWidth: 160 },
        },
        {
          id: 'serviceType',
          label: 'Service requested',
          type: 'select',
          required: true,
          options: [
            { label: 'Physiotherapy', value: 'physiotherapy' },
            { label: 'Occupational therapy', value: 'occupational-therapy' },
            { label: 'Speech pathology', value: 'speech-pathology' },
            { label: 'Exercise physiology', value: 'exercise-physiology' },
            { label: 'Dietitian', value: 'dietitian' },
          ],
          pdf: { mode: 'overlay', page: 0, x: 145, y: 481, size: 11, maxWidth: 380 },
        },
        {
          id: 'fundingType',
          label: 'Funding type',
          type: 'radio',
          required: true,
          options: [
            { label: 'NDIS', value: 'ndis' },
            { label: 'Medicare', value: 'medicare' },
            { label: 'Private', value: 'private' },
            { label: 'Workers compensation', value: 'workers-compensation' },
          ],
          pdf: {
            mode: 'overlay',
            page: 0,
            x: 145,
            y: 451,
            renderAs: 'radio',
            optionMap: {
              ndis: { x: 147, y: 449 },
              medicare: { x: 224, y: 449 },
              private: { x: 324, y: 449 },
              'workers-compensation': { x: 412, y: 449 },
            },
          },
        },
      ],
    },
    {
      id: 'request',
      title: 'Clinical Request',
      description: 'Keep the reason concise enough to fit the mapped PDF area.',
      fields: [
        {
          id: 'clinicalReason',
          label: 'Clinical reason for referral',
          type: 'textarea',
          required: true,
          autocomplete: 'off',
          validation: { maxLength: 350 },
          placeholder: 'Summarise the current issue, relevant history, and reason for referral.',
          pdf: {
            mode: 'overlay',
            page: 0,
            x: 72,
            y: 374,
            size: 10,
            maxWidth: 460,
            lineHeight: 13,
          },
        },
        {
          id: 'functionalGoals',
          label: 'Functional goals',
          type: 'textarea',
          autocomplete: 'off',
          validation: { maxLength: 180 },
          placeholder: 'Add goals or expected outcomes if known.',
          pdf: {
            mode: 'overlay',
            page: 0,
            x: 72,
            y: 248,
            size: 10,
            maxWidth: 460,
            lineHeight: 13,
          },
        },
        {
          id: 'consentToShare',
          label: 'Patient consent to share this referral information',
          type: 'checkbox',
          required: true,
          helpText: 'Required before generating the demo PDF.',
          pdf: { mode: 'overlay', page: 0, x: 56, y: 206, renderAs: 'checkbox' },
        },
        {
          id: 'urgent',
          label: 'Urgent request',
          type: 'checkbox',
          pdf: { mode: 'overlay', page: 0, x: 56, y: 183, renderAs: 'checkbox' },
        },
      ],
    },
  ],
};
